kind: pipeline
type: docker
name: npm-website

steps:
- name: build
  image: node:latest
  commands:
  - npm install express
  - npm install
  - npm test

trigger:
  event:
  - push

---
kind: pipeline
type: docker
name: deploy

steps:
- name: deployment
  image: node:latest
  commands:
  - npm install
  - npm start

trigger:
  event:
  - promote
  target:
  - production