kind: pipeline
type: docker
name: build

steps:
- name: drone-build
  image: node:latest
  commands:
  - npm install express
  - npm install
  - npm test

---
kind: pipeline
type: docker
name: deploy

steps:
- name: drone-deploy
  image: node:latest
  commands:
  - npm install express
  - npm install
  - npm start

trigger:
  event:
  - promote
  target:
  - production