version: "3"

networks:
  webserver-network:
    external: false
    name: webserver-network

services:
  default-webserver:
    image: node-docker
    container_name: default-webserver
    restart: "unless-stopped"
    user: "node"
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    networks:
      - webserver-network
